/*
If your program fails in a way that is not recoverable, you can call the panic macro to
immediately quit the program and return a message
*/

fn main() {
    panic!("crash and burn")
}
